config:
  info: "master branch,springcloud-config/config-dev.yml version=1"

config:
  info: "master branch,springcloud-config/config-prod.yml version=1"

config:
  info: "master branch,springcloud-config/config-test.yml version=1"
